### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by KristyNerhaugen** [McAmy2001/Where-Were-You-When#16]
- Decide on styling for application
- Implement styling

**Comment by KristyNerhaugen** [comment]
Instructions from project requirements: 
Instead of using a CSS library like Bootstrap, consider one of the following suggestions:

Look into the concept of CSS-in-JS, which abstracts CSS to the component level, using JavaScript to describe styles in a declarative and maintainable way. Some popular libraries include [styled-componentsLinks to an external site.](https://styled-components.com/) and [EmotionLinks to an external site.](https://emotion.sh/docs/introduction).

Try using a component library, such as [Semantic UILinks to an external site.](https://semantic-ui.com/), [Chakra UILinks to an external site.](https://chakra-ui.com/), or [Ant DesignLinks to an external site.](https://ant.design/).

Create all the CSS for your application just using CSS.

**Comment by kaylab78** [comment]
On Sunday, September 25, my tutor recommended using React-Bootstrap because we're still very new at using React and GraphQL. She said this is a big project and introducing a new styling could be difficult.
